language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
script: "npm run $TEST_STEP"
env:
  matrix:
    - TEST_STEP=lint
    - TEST_STEP=csslint
    - TEST_STEP=test
    - TEST_STEP=coveralls
